<?xml version="1.0" encoding="utf-8"?>
<DataListDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DataList.xsd" Version="1.00">
  <DataList Id="8dd4513c-c385-4507-bfee-5ab5ef56fcbc" ConfigurationUri="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/76d02814-95b7-4572-9618-565560f2a67f" PlcIdentifier="942b600f-699a-4fad-8204-ed13529ee8c5" TargetAttributes="PlcNext">
    <Datum Uuid="cfb1dca0-a79d-4f29-b600-e99900a036eb">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=iodpdin]" SourceId="5e32c7ab-4c04-4d09-953a-b4c8fe795d7a">
        <Label>~AI32</Label>
        <Access>I</Access>
        <DataType>Bitstring32</DataType>
        <Offset>0.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / aio-1 / ~AI32</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="ab72c6b0-a3a9-4c57-ba06-43b8b02fdfcf">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=io0]" SourceId="5e32c7ab-4c04-4d09-953a-b4c8fe795d7a">
        <Label>IN01</Label>
        <Access>I</Access>
        <DataType>Bitstring16</DataType>
        <Offset>0.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / aio-1 / IN01</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="001f4fe2-bd72-4208-9ba3-0a69d4c9784c">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=io1]" SourceId="5e32c7ab-4c04-4d09-953a-b4c8fe795d7a">
        <Label>IN02</Label>
        <Access>I</Access>
        <DataType>Bitstring16</DataType>
        <Offset>2.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / aio-1 / IN02</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="26b8f686-9219-40a6-b869-d41f9099d6ee">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=io2]" SourceId="5e32c7ab-4c04-4d09-953a-b4c8fe795d7a">
        <Label>~AQ32</Label>
        <Access>Q</Access>
        <DataType>Bitstring32</DataType>
        <Offset>0.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / aio-1 / ~AQ32</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="f6098777-f210-4666-b1da-d049cf5de2cb">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=io3]" SourceId="5e32c7ab-4c04-4d09-953a-b4c8fe795d7a">
        <Label>OUT01</Label>
        <Access>Q</Access>
        <DataType>Bitstring16</DataType>
        <Offset>0.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / aio-1 / OUT01</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="32382aa2-1e58-4fdc-982b-d8b875529c9d">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=io4]" SourceId="5e32c7ab-4c04-4d09-953a-b4c8fe795d7a">
        <Label>OUT02</Label>
        <Access>Q</Access>
        <DataType>Bitstring16</DataType>
        <Offset>2.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / aio-1 / OUT02</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="f1c622e7-7265-403b-a1e6-822dfb813f8a">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=iodpdin]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>~DI8</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset>1.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / ~DI8</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="64cd8bd8-d1a4-4526-943d-100ad3c6dc19">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=iodpdout]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>~DO8</Label>
        <Access>Q</Access>
        <DataType>Bitstring8</DataType>
        <Offset>1.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / ~DO8</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="5fa3fbce-6a71-4e11-bb98-0b0028f54a00">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=io0]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>IN00</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / IN00</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="892c73bd-e594-48b2-b9a3-a29b7de47b19">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=io1]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>IN01</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.1</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / IN01</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="5b0c955f-6d33-48d5-a71e-38a676ec0bc7">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=io2]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>IN02</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.2</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / IN02</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="ef5d9597-025d-49f3-a6e1-21aebba5cb46">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=io3]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>IN03</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.3</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / IN03</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="d74e3b01-e065-4a32-8b2d-b2554768a418">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=io4]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>IN04</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.4</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / IN04</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="7a620aee-d608-4efa-9a08-1009f481a0ae">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=io5]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>IN05</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.5</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / IN05</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="37fd99b4-4669-4d55-b3a7-139acbe66774">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=io6]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>IN06</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.6</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / IN06</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="2f89e55e-c557-4d41-9e5d-5f579d9eb306">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=io7]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>IN07</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.7</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / IN07</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="88854d36-4fc8-426c-8e5e-834969063ddc">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=io8]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>OUT00</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / OUT00</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
      <Role TypeName="Variable" ObjectId="0be8e67b-0a74-4cc6-858a-e79c59f44426" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>Zone1</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.Zone1</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Name,Usage,DataType,InitValue,IsRetain,Comment,IsOpc,IsConstant,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="HmiTag" ObjectId="6301706d-edae-49d9-80a0-c062989d37dd" SourceId="">
        <IsReadOnly>False</IsReadOnly>
        <DisplayName>Zone1</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="DisplayName,IsReadOnly" />
      </Role>
    </Datum>
    <Datum Uuid="45347044-77eb-432a-9a90-94e884d25423">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=io9]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>OUT01</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.1</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / OUT01</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="985e93e1-4d07-4d5c-86ba-9f9521bb90d1">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=io10]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>OUT02</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.2</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / OUT02</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="38f91019-fef0-427d-bc2a-9e7c4b51a69f">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="13" ObjectId="/PDList/PD[@uid=io11]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>OUT03</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.3</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / OUT03</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="775e41a0-6d7a-442a-bfbd-166aeb9cd8cf">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="14" ObjectId="/PDList/PD[@uid=io12]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>OUT04</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.4</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / OUT04</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="c7776c68-0532-4ef3-9367-e8b816a45094">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="15" ObjectId="/PDList/PD[@uid=io13]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>OUT05</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.5</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / OUT05</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="23f1cc2b-157b-480f-a88f-a5be4d824ff3">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="16" ObjectId="/PDList/PD[@uid=io14]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>OUT06</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.6</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / OUT06</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="e1c0f519-da91-49fc-a288-b1cd993e9f36">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="17" ObjectId="/PDList/PD[@uid=io15]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Label>OUT07</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.7</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / dio-1 / OUT07</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="7f8482ec-6ab5-4357-8946-08a697dba884">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="fa815cda-4727-4965-b2a9-80e3b6635655" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PND_S1_PLC_RUN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment>Higher level PLC in RUN</Comment>
        <DisplayName>The Ruth Automation Controller / PLC.PND_S1_PLC_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pndpd1]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PND_S1_PLC_RUN</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PND_S1_PLC_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="e59d37f1-e6f9-477d-b610-2fde53630f93">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="557f9710-406b-4abb-8af2-a50b75a8fb3e" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PND_S1_VALID_DATA_CYCLE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment>Connection to Profinet-Controller</Comment>
        <DisplayName>The Ruth Automation Controller / PLC.PND_S1_VALID_DATA_CYCLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pndpd2]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PND_S1_VALID_DATA_CYCLE</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PND_S1_VALID_DATA_CYCLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="593d3bcc-92c1-4fbf-9149-87c75f631fc0">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="dfff7161-e34d-4720-8457-96836fada337" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PND_S1_OUTPUT_STATUS_GOOD</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment>IOP status of the higher-level control system</Comment>
        <DisplayName>The Ruth Automation Controller / PLC.PND_S1_OUTPUT_STATUS_GOOD</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pndpd3]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PND_S1_OUTPUT_STATUS_GOOD</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PND_S1_OUTPUT_STATUS_GOOD</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ed96c6bc-c21c-43d3-8e9c-c7336144079d">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="12203f47-dba9-4b06-8e0d-89396264ac1e" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PND_S1_INPUT_STATUS_GOOD</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment>IOC status of the higher-level control system</Comment>
        <DisplayName>The Ruth Automation Controller / PLC.PND_S1_INPUT_STATUS_GOOD</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pndpd4]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PND_S1_INPUT_STATUS_GOOD</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PND_S1_INPUT_STATUS_GOOD</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="420b6b3d-a1b9-45ae-a809-84beadda5525">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="b294e650-f20e-4ca3-b254-0acf45c08ffc" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PND_S1_DATA_LENGTH</Name>
        <Usage>Global</Usage>
        <DataType>WORD</DataType>
        <Address />
        <InitValue>WORD#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment>Process data length</Comment>
        <DisplayName>The Ruth Automation Controller / PLC.PND_S1_DATA_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=pndpd5]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PND_S1_DATA_LENGTH</Label>
        <Access>I</Access>
        <DataType>Bitstring16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PND_S1_DATA_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="1b389238-ba91-45f3-aead-c14c624861aa">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="945dd062-4ca9-49b7-8d40-ccebc2fca8e0" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PND_S1_OUTPUTS</Name>
        <Usage>Global</Usage>
        <DataType>PND_IO_512</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment>Output process data</Comment>
        <DisplayName>The Ruth Automation Controller / PLC.PND_S1_OUTPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=pndpd6]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PND_S1_OUTPUTS</Label>
        <Access>Q</Access>
        <DataType>Octetstring[512]</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PND_S1_OUTPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ce0d4384-7844-4df7-82b6-9a4b293db338">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="8a9cf966-0ea0-4374-9f48-92729642daf0" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PND_S1_INPUTS</Name>
        <Usage>Global</Usage>
        <DataType>PND_IO_512</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment>Input process data</Comment>
        <DisplayName>The Ruth Automation Controller / PLC.PND_S1_INPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=pndpd7]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PND_S1_INPUTS</Label>
        <Access>I</Access>
        <DataType>Octetstring[512]</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PND_S1_INPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="47d9a5e4-8e7b-4238-be40-d48c23209dad">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="00ccb10b-cb1d-4c05-93bc-fc96cacbad37" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PND_IO_DRIVEN_BY_PLC</Name>
        <Usage>Global</Usage>
        <DataType>INT</DataType>
        <Address />
        <InitValue>INT#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.PND_IO_DRIVEN_BY_PLC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=pndpd8]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PND_IO_DRIVEN_BY_PLC</Label>
        <Access>I</Access>
        <DataType>Signed16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PND_IO_DRIVEN_BY_PLC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="e87ab2d6-a092-47bf-af69-3a2ee27b64bd">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="4575a587-2067-4253-a6c9-46604072f58d" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>AXIO_DIAG_STATUS_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.AXIO_DIAG_STATUS_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=axiod0]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Axioline F / AXIO_DIAG_STATUS_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="4b6a35e5-d311-4c12-8ab8-bce7c42cc9c0">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="7a379785-e399-4db2-a94a-4d5ec05c4a0b" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>AXIO_DIAG_STATUS_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.AXIO_DIAG_STATUS_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=axiod1]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Axioline F / AXIO_DIAG_STATUS_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="570c268c-f229-4c6d-ba3a-4c3561752e10">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="1f933763-c00b-4804-9511-5142b860b467" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>AXIO_DIAG_PARAM_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.AXIO_DIAG_PARAM_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=axiod2]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_ax">
        <Label>AXIO_DIAG_PARAM_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Axioline F / AXIO_DIAG_PARAM_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="5aee512f-5060-4faa-82f4-69395aa7defe">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="5594a1ba-b171-41e4-becf-0c046344dfef" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>AXIO_DIAG_PARAM_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.AXIO_DIAG_PARAM_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=axiod3]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_ax">
        <Label>AXIO_DIAG_PARAM_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Axioline F / AXIO_DIAG_PARAM_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="c0060c39-5b19-4aca-b45d-558aa2cbb7b6">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="9cd72b70-52ff-4724-b5b2-72c9a95ca7bf" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>AXIO_DIAG_PARAM_2_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.AXIO_DIAG_PARAM_2_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=axiod4]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_ax">
        <Label>AXIO_DIAG_PARAM_2_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Axioline F / AXIO_DIAG_PARAM_2_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="cc8af953-3a50-428d-b019-8a6d58e91c72">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="0c73656e-0135-4859-b07b-3fe4d686dcb9" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>AXIO_DIAG_PARAM_2_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.AXIO_DIAG_PARAM_2_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=axiod5]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_ax">
        <Label>AXIO_DIAG_PARAM_2_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Axioline F / AXIO_DIAG_PARAM_2_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="8c83e449-957f-4743-881d-936e1335812c">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="58f5c02b-c360-44c9-96b5-ef0c694569e3" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>AXIO_DIAG_STATUS_REG_PF</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.AXIO_DIAG_STATUS_REG_PF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=axiod6]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_PF</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Axioline F / AXIO_DIAG_STATUS_REG_PF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="142bd296-c209-4fa9-86fe-a5ce408462e5">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="35db4f90-976e-4b25-95d1-acb459570ffa" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>AXIO_DIAG_STATUS_REG_BUS</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.AXIO_DIAG_STATUS_REG_BUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=axiod7]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_BUS</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Axioline F / AXIO_DIAG_STATUS_REG_BUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="58876e10-3a15-4c82-b89a-21a79c2d8724">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="fb0e7a05-16a7-4a88-aeec-f6f416cdade9" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>AXIO_DIAG_STATUS_REG_RUN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.AXIO_DIAG_STATUS_REG_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=axiod8]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_RUN</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Axioline F / AXIO_DIAG_STATUS_REG_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="6285e484-76a1-44c0-ac93-5265e0e13227">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="67304b02-e187-4557-821c-c8527e58c510" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>AXIO_DIAG_STATUS_REG_ACT</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.AXIO_DIAG_STATUS_REG_ACT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=axiod9]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_ACT</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Axioline F / AXIO_DIAG_STATUS_REG_ACT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="7b063dec-c970-4128-ad54-ccf9d80aa272">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="2264ee1f-dcbe-4ac8-b025-af5191c154ba" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>AXIO_DIAG_STATUS_REG_RDY</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.AXIO_DIAG_STATUS_REG_RDY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=axiod10]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_RDY</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Axioline F / AXIO_DIAG_STATUS_REG_RDY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="1eb1a644-acad-44ce-9630-f84114bbb17e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ff001b99-b7ed-4dbb-bab5-4b9b6bef949b" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>AXIO_DIAG_STATUS_REG_SYSFAIL</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.AXIO_DIAG_STATUS_REG_SYSFAIL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=axiod11]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_SYSFAIL</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Axioline F / AXIO_DIAG_STATUS_REG_SYSFAIL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="2ad1be64-7592-464c-af09-5c0dd7a5a83d">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="a7cd4fad-7f67-44eb-8045-0a3b526e9789" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>AXIO_DIAG_STATUS_REG_PW</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.AXIO_DIAG_STATUS_REG_PW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=axiod12]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_PW</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Axioline F / AXIO_DIAG_STATUS_REG_PW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="0d3ba8e2-3503-42d9-aba9-42526072fe56">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="977e075f-8043-405e-9bc8-6dd764ffa667" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_STATUS_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_STATUS_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pdib1]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_STATUS_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="d60393ac-7b9b-447b-83fa-e89e66e029d9">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ed835410-814c-4193-82d7-c5ee2be79409" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_STATUS_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_STATUS_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pdib2]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_STATUS_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="10fa755d-1f3c-46bb-8837-79750c31d4a8">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="1d46d8b9-e1ba-44dd-a1be-009c921334d0" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_STATUS_REG_SYSFAIL</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_STATUS_REG_SYSFAIL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pdib3]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_STATUS_REG_SYSFAIL</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_SYSFAIL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="832d10bc-fe88-4797-9ba5-25f6d459f1dd">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="39f3a240-f518-4451-aa0f-26bd86253cf8" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_STATUS_REG_WARN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_STATUS_REG_WARN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pdib4]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_STATUS_REG_WARN</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_WARN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="9c49a883-3b21-4ace-81da-79fd083e6799">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="8ef68cfa-0b9e-472d-95ce-324af8721552" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_STATUS_REG_QUAL</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_STATUS_REG_QUAL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=pdib5]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_STATUS_REG_QUAL</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_QUAL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="78a86e71-5bff-4325-81ea-0c33d2124a01">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="331d3ce6-e810-4fed-b020-7c2f0ae75370" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_STATUS_REG_USER</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_STATUS_REG_USER</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=pdib6]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_STATUS_REG_USER</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_USER</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="77565506-16a0-4259-aff6-6a8b41e92f6c">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="39ab4da3-b759-438d-b211-0a16b3456bea" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_STATUS_REG_PF</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_STATUS_REG_PF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=pdib7]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_STATUS_REG_PF</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_PF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="d00ec26e-076a-45e9-b249-c780634a24c0">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="4e03c41c-73e7-4ee8-a8bf-8b4e70aa732e" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_STATUS_REG_BUS</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_STATUS_REG_BUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=pdib8]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_STATUS_REG_BUS</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_BUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="be41bf67-9f24-40b5-a887-5f091eff3961">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="11d8bf36-2ad8-46e9-a327-50337dc7b5bc" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_STATUS_REG_CTRL</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_STATUS_REG_CTRL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=pdib9]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_STATUS_REG_CTRL</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_CTRL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="7f8cc197-9f07-45ed-9c49-fa959e39ee5b">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="4be8a007-f8d0-44e0-9dd6-db29e373249c" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_STATUS_REG_DTC</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_STATUS_REG_DTC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=pdib10]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_STATUS_REG_DTC</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_DTC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="1bedcedd-fb49-4c37-9417-b37d58eca818">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="e1667263-93ac-4b8a-b491-3eeb7a0e68ee" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_STATUS_REG_RUN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_STATUS_REG_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=pdib11]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_STATUS_REG_RUN</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="5b9b4f41-ea11-4b42-bc5c-d4eb29a3069b">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="723c3093-cc01-46ba-8409-ce5b9ee8c100" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_STATUS_REG_ACT</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_STATUS_REG_ACT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=pdib12]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_STATUS_REG_ACT</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_ACT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="7bcb2eb6-8159-440c-821a-5ee5ada18334">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="36cd45ba-60a0-4263-8a99-9abc5eff7e96" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_STATUS_REG_RDY</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_STATUS_REG_RDY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=pdib13]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_STATUS_REG_RDY</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_RDY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="0aaccaae-a124-4f3e-acdf-f4acf1616ff3">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="3ef10dfe-45a5-4219-9035-602d6795dd2c" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_PARAM_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_PARAM_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="13" ObjectId="/PDList/PD[@uid=pdib14]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_PARAM_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_PARAM_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="26da0186-8ea4-40ed-87e7-e32645be7f25">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="5dbe0c21-4b63-4dba-9daf-118177f290d3" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_PARAM_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_PARAM_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="14" ObjectId="/PDList/PD[@uid=pdib15]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_PARAM_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_PARAM_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="3555088d-cc17-4524-b294-71711fa66d4c">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="409d7e77-de54-48c0-bb05-282fbac80538" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_PARAM_2_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_PARAM_2_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="15" ObjectId="/PDList/PD[@uid=pdib16]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_PARAM_2_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_PARAM_2_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="95074c74-9a70-4b22-bbd4-cf1182a53243">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="759753c1-6ce9-4a30-a5e6-a80de4d7a910" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IB_DIAG_PARAM_2_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IB_DIAG_PARAM_2_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="16" ObjectId="/PDList/PD[@uid=pdib17]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_8">
        <Label>IB_DIAG_PARAM_2_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / AXC F IL ADAPT / AXC XT IB / IB_DIAG_PARAM_2_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="c24ad942-0b1b-45b3-a73c-d98089ad76b7">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f522aedd-a423-43e7-8bcc-7cf590d9ad48" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>ESM_DATA</Name>
        <Usage>Global</Usage>
        <DataType>ESM_DAT</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.ESM_DATA</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pdesm1]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_1">
        <Label>ESM_DATA</Label>
        <Access>I</Access>
        <DataType>ESM_DAT</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / PLCnext / ESM_DATA</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="2d8d27d5-ea15-42b0-a873-91263054d751">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="6af71bc0-e1d8-4f76-9150-b05998e9d38c" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>RTC</Name>
        <Usage>Global</Usage>
        <DataType>RTC_TYPE</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.RTC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pddi1]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_1">
        <Label>RTC</Label>
        <Access>I</Access>
        <DataType>RTC_TYPE</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / PLCnext / RTC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="0e057c39-7720-4931-b80b-7d01321f4316">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="4007874f-7c79-49de-8408-068da7e4f0ef" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>DEVICE_STATE</Name>
        <Usage>Global</Usage>
        <DataType>DEVICE_STATE_2152_TYPE</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.DEVICE_STATE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pddi2]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_1">
        <Label>DEVICE_STATE</Label>
        <Access>I</Access>
        <DataType>DEVICE_STATE_2152_TYPE</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / PLCnext / DEVICE_STATE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="a44b24b7-2bec-453f-a3a9-88e31d621f98">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="726ac91e-b842-4862-b2ef-106f4ee5ac88" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>USER_PARTITION</Name>
        <Usage>Global</Usage>
        <DataType>PARTITION_INFO</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.USER_PARTITION</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pddi4]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_1">
        <Label>USER_PARTITION</Label>
        <Access>I</Access>
        <DataType>PARTITION_INFO</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / PLCnext / USER_PARTITION</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="3022fa29-199c-48b8-b6ce-3762bff952e9">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="97f3a7aa-c56b-4063-94e9-302183413cd4" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PNIO_SYSTEM_BF</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.PNIO_SYSTEM_BF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=pncpd1]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PNIO_SYSTEM_BF</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PNIO_SYSTEM_BF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="c17c43d9-96e0-4401-9800-36f4e40737ae">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="66818d2d-f7c7-4c04-9926-7556e393e723" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PNIO_SYSTEM_SF</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.PNIO_SYSTEM_SF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=pncpd2]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PNIO_SYSTEM_SF</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PNIO_SYSTEM_SF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="1a11bf17-7335-45a7-a9c7-bbbcfcee22fa">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="24d59b84-0860-4bab-84ad-8c7a54221670" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PNIO_MAINTENANCE_DEMANDED</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.PNIO_MAINTENANCE_DEMANDED</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=pncpd3]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PNIO_MAINTENANCE_DEMANDED</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PNIO_MAINTENANCE_DEMANDED</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="03639047-8d4f-4fc0-a0df-1bd20bf01cf1">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="e74861c2-2b8d-4849-88ce-08b07b29602f" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PNIO_MAINTENANCE_REQUIRED</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.PNIO_MAINTENANCE_REQUIRED</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=pncpd4]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PNIO_MAINTENANCE_REQUIRED</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PNIO_MAINTENANCE_REQUIRED</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="993c6f6c-4cb7-4cb4-874a-6559e7783093">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="909ae4dc-6e26-437d-bbf9-7f73804db4e8" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PNIO_CONFIG_STATUS</Name>
        <Usage>Global</Usage>
        <DataType>WORD</DataType>
        <Address />
        <InitValue>WORD#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.PNIO_CONFIG_STATUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=pncpd5]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PNIO_CONFIG_STATUS</Label>
        <Access>I</Access>
        <DataType>Bitstring16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PNIO_CONFIG_STATUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="24638351-de41-47fe-a7de-d196789602aa">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="6e8f4e26-4b3a-4257-9043-14f36fde1702" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PNIO_CONFIG_STATUS_ACTIVE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.PNIO_CONFIG_STATUS_ACTIVE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="13" ObjectId="/PDList/PD[@uid=pncpd6]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PNIO_CONFIG_STATUS_ACTIVE</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PNIO_CONFIG_STATUS_ACTIVE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ef65d3f5-b16f-47bf-8f36-f5144fa9529e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="cc3d973e-e98a-4454-a60f-6a37427d1946" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PNIO_CONFIG_STATUS_READY</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.PNIO_CONFIG_STATUS_READY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="14" ObjectId="/PDList/PD[@uid=pncpd7]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PNIO_CONFIG_STATUS_READY</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PNIO_CONFIG_STATUS_READY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="00a6938f-a02d-4664-acd6-320a24c7d8b3">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ea96a2bc-d1f7-4f44-89c1-10899b262ff8" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PNIO_CONFIG_STATUS_CFG_FAULT</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.PNIO_CONFIG_STATUS_CFG_FAULT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="15" ObjectId="/PDList/PD[@uid=pncpd8]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PNIO_CONFIG_STATUS_CFG_FAULT</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PNIO_CONFIG_STATUS_CFG_FAULT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="efce0383-7068-4ce9-bd86-da1172b259e5">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="bd3cc2f6-db5e-4781-9948-af881bd46428" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PNIO_FORCE_FAILSAFE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.PNIO_FORCE_FAILSAFE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="16" ObjectId="/PDList/PD[@uid=pncpd9]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PNIO_FORCE_FAILSAFE</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PNIO_FORCE_FAILSAFE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="637e2e2c-c05f-4297-a24c-7a275768313e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="1a7290f9-2065-4d29-961e-08a45df50e50" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>PNIO_FORCE_PRIMARY</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.PNIO_FORCE_PRIMARY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="17" ObjectId="/PDList/PD[@uid=pncpd10]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_4">
        <Label>PNIO_FORCE_PRIMARY</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / Profinet / PNIO_FORCE_PRIMARY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="535a3a77-2b10-43af-87c6-49b50cf03165">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ef8c7e80-8535-4b65-b13d-c675fc6cf6aa" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>IP_ACTIVE_SOCKETS</Name>
        <Usage>Global</Usage>
        <DataType>UINT</DataType>
        <Address>%MW1.30000</Address>
        <InitValue>UINT#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.IP_ACTIVE_SOCKETS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
        <Constraint TypeName="Ade.DataList.Constraints.Unconnectable, Ade.DataListImpl" Parameters="ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="323320ea-49aa-47b9-aaa0-36f5fdd8b7bf">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="980aea0c-10d6-45e1-ad63-a450de1a6216" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>TLS_ACTIVE_SOCKETS</Name>
        <Usage>Global</Usage>
        <DataType>UINT</DataType>
        <Address>%MW1.30100</Address>
        <InitValue>UINT#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.TLS_ACTIVE_SOCKETS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
        <Constraint TypeName="Ade.DataList.Constraints.Unconnectable, Ade.DataListImpl" Parameters="ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="80fcf98f-91b0-493b-bb7c-32e0d8458b71">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="a09e0fc8-dc4f-4ea3-83f6-77463756da4e" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>HMI_STATUS</Name>
        <Usage>Global</Usage>
        <DataType>HMI_STATUS_TYPE</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.HMI_STATUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=hmipd001]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_3">
        <Label>HMI_STATUS</Label>
        <Access>I</Access>
        <DataType>HMI_STATUS_TYPE</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / HMI Webserver / HMI_STATUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="8d274ac0-3077-45ba-acb7-2eb347c4e330">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f4d30420-65d7-467c-a6bc-51d970217212" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>HMI_CONTROL</Name>
        <Usage>Global</Usage>
        <DataType>HMI_CONTROL_TYPE</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.HMI_CONTROL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=hmipd002]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_3">
        <Label>HMI_CONTROL</Label>
        <Access>Q</Access>
        <DataType>HMI_CONTROL_TYPE</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>The Ruth Automation Controller / HMI Webserver / HMI_CONTROL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="a772e3f4-ddbc-497a-b930-d468ab30f874">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="77162036-fc66-40b7-a130-ae91a017a6a6" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>EIPD_INPUTS</Name>
        <Usage>Global</Usage>
        <DataType>EIPD_IO_ARRAY</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.EIPD_INPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=eip001]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_7">
        <Label>EIPD_INPUTS</Label>
        <Access>I</Access>
        <DataType>EIPD_IO_ARRAY</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_INPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="b4d86a17-affc-433b-8756-3d001550c88a">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="5176cf01-140f-4a8c-b0a6-72e8d84c27cd" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>EIPD_OUTPUTS</Name>
        <Usage>Global</Usage>
        <DataType>EIPD_IO_ARRAY</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.EIPD_OUTPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=eip002]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_7">
        <Label>EIPD_OUTPUTS</Label>
        <Access>Q</Access>
        <DataType>EIPD_IO_ARRAY</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_OUTPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="a50a7a96-7023-4bf3-81dc-f2871639bbc2">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="51c4595f-a72b-45c2-991e-572b56395fa0" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>EIPD_VALID_DATA_CYCLE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.EIPD_VALID_DATA_CYCLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=eip003]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_7">
        <Label>EIPD_VALID_DATA_CYCLE</Label>
        <Access>I</Access>
        <DataType>Boolean</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_VALID_DATA_CYCLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ba6642f2-dbc3-4fbb-8664-b3606ada8a8e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="830cd8ef-2133-442d-9f13-d47e0362bd65" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>EIPD_PEER_IDLE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.EIPD_PEER_IDLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=eip004]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_7">
        <Label>EIPD_PEER_IDLE</Label>
        <Access>I</Access>
        <DataType>Boolean</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_PEER_IDLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="2406d650-9ce2-4294-b9e8-091554f9bd71">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="cd737f91-7a68-4a44-ab0d-9cb171f1c8e5" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>EIPD_PEER_RUN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.EIPD_PEER_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=eip005]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_7">
        <Label>EIPD_PEER_RUN</Label>
        <Access>I</Access>
        <DataType>Boolean</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_PEER_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ba0316c5-0b23-4559-b4b9-23e983369f45">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="da177645-f9ce-41ea-9294-958bdac4d091" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>EIPD_OUTPUTS_LENGTH</Name>
        <Usage>Global</Usage>
        <DataType>WORD</DataType>
        <Address />
        <InitValue>WORD#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.EIPD_OUTPUTS_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=eip006]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_7">
        <Label>EIPD_OUTPUTS_LENGTH</Label>
        <Access>I</Access>
        <DataType>Bitstring16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_OUTPUTS_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="11f51265-1fd9-46d2-8012-934ef456fab8">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="6f298ac5-bac7-4047-a58d-8e45368e88a0" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>EIPD_INPUTS_LENGTH</Name>
        <Usage>Global</Usage>
        <DataType>WORD</DataType>
        <Address />
        <InitValue>WORD#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.EIPD_INPUTS_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=eip007]" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_7">
        <Label>EIPD_INPUTS_LENGTH</Label>
        <Access>I</Access>
        <DataType>Bitstring16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_INPUTS_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="e18e4ab0-dfb8-4f91-acb0-8e180686d925">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="cd0c2be0-d01e-40c7-8661-5499de7b4af2" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154">
        <Name>ButtonThing</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>True</IsProficloud>
        <Comment />
        <DisplayName>The Ruth Automation Controller / PLC.ButtonThing</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Name,Usage,DataType,InitValue,IsRetain,Comment,IsOpc,IsConstant,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="HmiTag" ObjectId="e2d7055b-de69-4d9e-bf0e-35727279dc69" SourceId="">
        <IsReadOnly>False</IsReadOnly>
        <DisplayName>ButtonThing</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="DisplayName,IsReadOnly" />
      </Role>
    </Datum>
    <Datum Uuid="1d0864c7-6385-4017-a8b3-8b3c8d88dcf2">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="c8da7876-b701-4a7c-b5fc-553d24388856" SourceId="942b600f-699a-4fad-8204-ed13529ee8c5.L7_2">
        <Name>ButtonThing</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>MainInstance</ProgramInstance>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <DisplayName>Arp.Plc.Eclr / MainInstance : ButtonThing</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="d4a448a7-d0bc-42f6-8660-b7f5baf2ceae">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io2]" SourceId="5e32c7ab-4c04-4d09-953a-b4c8fe795d7a">
        <Name>~AQ32</Name>
        <DataType>Bitstring32</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Bitstring32</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>0.0</Offset>
        <NodeId>0</NodeId>
        <DisplayName>The Ruth Automation Controller / aio-1 / ~AQ32</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="36c365fe-4633-474a-9b5a-1aa2b85e49f8">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io3]" SourceId="5e32c7ab-4c04-4d09-953a-b4c8fe795d7a">
        <Name>OUT01</Name>
        <DataType>Bitstring16</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Bitstring16</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>0.0</Offset>
        <NodeId>0</NodeId>
        <DisplayName>The Ruth Automation Controller / aio-1 / OUT01</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="1a4785ca-3948-4ad8-9300-a2b66510bc40">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io4]" SourceId="5e32c7ab-4c04-4d09-953a-b4c8fe795d7a">
        <Name>OUT02</Name>
        <DataType>Bitstring16</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Bitstring16</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>2.0</Offset>
        <NodeId>0</NodeId>
        <DisplayName>The Ruth Automation Controller / aio-1 / OUT02</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="b9664b07-aa21-4ebb-8745-b20cf6b19ae8">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=iodpdin]" SourceId="5e32c7ab-4c04-4d09-953a-b4c8fe795d7a">
        <Name>~AI32</Name>
        <DataType>Bitstring32</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Bitstring32</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>0.0</Offset>
        <NodeId>0</NodeId>
        <DisplayName>The Ruth Automation Controller / aio-1 / ~AI32</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="920b1cd1-ab86-4fca-8613-a31b495e2c88">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io0]" SourceId="5e32c7ab-4c04-4d09-953a-b4c8fe795d7a">
        <Name>IN01</Name>
        <DataType>Bitstring16</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Bitstring16</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>0.0</Offset>
        <NodeId>0</NodeId>
        <DisplayName>The Ruth Automation Controller / aio-1 / IN01</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="37f615f0-ec67-4f7a-b829-2854a1952b90">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io1]" SourceId="5e32c7ab-4c04-4d09-953a-b4c8fe795d7a">
        <Name>IN02</Name>
        <DataType>Bitstring16</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Bitstring16</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>2.0</Offset>
        <NodeId>0</NodeId>
        <DisplayName>The Ruth Automation Controller / aio-1 / IN02</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="f63f3fde-5366-4c87-b7e0-16206443176b">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=iodpdout]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>~DO8</Name>
        <DataType>Bitstring8</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Bitstring8</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.0</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / ~DO8</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="3b84b2fb-220b-4ed9-953f-ae0e612bdc67">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io8]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>OUT00</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.0</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / OUT00</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="80f8e94c-8aa4-4e52-a73f-69dd1874cbea">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io9]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>OUT01</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.1</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / OUT01</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="9133c2d8-f49c-45a6-b34d-b1a12d999b69">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io10]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>OUT02</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.2</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / OUT02</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="f306fdcd-0f2c-4f9a-92dc-2af1b2e9e406">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io11]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>OUT03</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.3</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / OUT03</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="860b3a76-2529-4242-8e32-f6caf7d33d2c">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io12]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>OUT04</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.4</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / OUT04</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="1ddfc3ef-be5c-4244-a89f-7185aeefce65">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io13]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>OUT05</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.5</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / OUT05</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="5a2fc567-60a5-4445-b671-87a9f360bcac">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io14]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>OUT06</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.6</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / OUT06</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="4b147e8f-306f-4aa7-a216-327607cb7d89">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io15]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>OUT07</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.7</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / OUT07</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="17d5d692-98fd-40bf-8a93-627e014918b1">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=iodpdin]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>~DI8</Name>
        <DataType>Bitstring8</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Bitstring8</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.0</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / ~DI8</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="c2a617df-ebb1-479e-b994-9e8b93523692">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io0]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>IN00</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.0</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / IN00</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="c6d91875-a942-4435-8269-a5eebfa698b5">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io1]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>IN01</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.1</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / IN01</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="028b887a-71a0-42bf-9db9-6931cb818b53">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io2]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>IN02</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.2</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / IN02</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="8c95db1a-c592-4c2b-9d5b-0ceda09db768">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io3]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>IN03</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.3</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / IN03</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="619e9b10-05f9-4187-8d2d-86c6210bcb85">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io4]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>IN04</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.4</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / IN04</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="2e4acded-81f1-47b6-8764-6721c64180e8">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io5]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>IN05</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.5</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / IN05</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="d78f80c9-8dea-4faf-a355-ccaa22396489">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io6]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>IN06</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.6</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / IN06</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="2fcac291-42d8-4863-97dd-63a3858c402e">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io7]" SourceId="8bf93a00-8717-4ef9-b880-668a219b9f4f">
        <Name>IN07</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.7</Offset>
        <NodeId>1</NodeId>
        <DisplayName>The Ruth Automation Controller / dio-1 / IN07</DisplayName>
      </Role>
    </Datum>
    <RoleGroupList RoleTypeName="Variable">
      <RoleGroup SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154" ObjectId="fb84caa8-36a3-47d9-8bf0-95ff0e8a7b24" DisplayName="Default" IsReadOnly="False">
        <RoleDatumUuid>e18e4ab0-dfb8-4f91-acb0-8e180686d925</RoleDatumUuid>
        <RoleDatumUuid>88854d36-4fc8-426c-8e5e-834969063ddc</RoleDatumUuid>
      </RoleGroup>
      <RoleGroup SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/5fda287b-0f42-4cd2-acf1-feb607546154" ObjectId="971398c9-e054-4349-a1d9-e00a1840c9f4" DisplayName="System Variables" IsReadOnly="True">
        <RoleDatumUuid>7f8482ec-6ab5-4357-8946-08a697dba884</RoleDatumUuid>
        <RoleDatumUuid>e59d37f1-e6f9-477d-b610-2fde53630f93</RoleDatumUuid>
        <RoleDatumUuid>593d3bcc-92c1-4fbf-9149-87c75f631fc0</RoleDatumUuid>
        <RoleDatumUuid>ed96c6bc-c21c-43d3-8e9c-c7336144079d</RoleDatumUuid>
        <RoleDatumUuid>420b6b3d-a1b9-45ae-a809-84beadda5525</RoleDatumUuid>
        <RoleDatumUuid>1b389238-ba91-45f3-aead-c14c624861aa</RoleDatumUuid>
        <RoleDatumUuid>ce0d4384-7844-4df7-82b6-9a4b293db338</RoleDatumUuid>
        <RoleDatumUuid>47d9a5e4-8e7b-4238-be40-d48c23209dad</RoleDatumUuid>
        <RoleDatumUuid>e87ab2d6-a092-47bf-af69-3a2ee27b64bd</RoleDatumUuid>
        <RoleDatumUuid>4b6a35e5-d311-4c12-8ab8-bce7c42cc9c0</RoleDatumUuid>
        <RoleDatumUuid>570c268c-f229-4c6d-ba3a-4c3561752e10</RoleDatumUuid>
        <RoleDatumUuid>5aee512f-5060-4faa-82f4-69395aa7defe</RoleDatumUuid>
        <RoleDatumUuid>c0060c39-5b19-4aca-b45d-558aa2cbb7b6</RoleDatumUuid>
        <RoleDatumUuid>cc8af953-3a50-428d-b019-8a6d58e91c72</RoleDatumUuid>
        <RoleDatumUuid>8c83e449-957f-4743-881d-936e1335812c</RoleDatumUuid>
        <RoleDatumUuid>142bd296-c209-4fa9-86fe-a5ce408462e5</RoleDatumUuid>
        <RoleDatumUuid>58876e10-3a15-4c82-b89a-21a79c2d8724</RoleDatumUuid>
        <RoleDatumUuid>6285e484-76a1-44c0-ac93-5265e0e13227</RoleDatumUuid>
        <RoleDatumUuid>7b063dec-c970-4128-ad54-ccf9d80aa272</RoleDatumUuid>
        <RoleDatumUuid>1eb1a644-acad-44ce-9630-f84114bbb17e</RoleDatumUuid>
        <RoleDatumUuid>2ad1be64-7592-464c-af09-5c0dd7a5a83d</RoleDatumUuid>
        <RoleDatumUuid>0d3ba8e2-3503-42d9-aba9-42526072fe56</RoleDatumUuid>
        <RoleDatumUuid>d60393ac-7b9b-447b-83fa-e89e66e029d9</RoleDatumUuid>
        <RoleDatumUuid>10fa755d-1f3c-46bb-8837-79750c31d4a8</RoleDatumUuid>
        <RoleDatumUuid>832d10bc-fe88-4797-9ba5-25f6d459f1dd</RoleDatumUuid>
        <RoleDatumUuid>9c49a883-3b21-4ace-81da-79fd083e6799</RoleDatumUuid>
        <RoleDatumUuid>78a86e71-5bff-4325-81ea-0c33d2124a01</RoleDatumUuid>
        <RoleDatumUuid>77565506-16a0-4259-aff6-6a8b41e92f6c</RoleDatumUuid>
        <RoleDatumUuid>d00ec26e-076a-45e9-b249-c780634a24c0</RoleDatumUuid>
        <RoleDatumUuid>be41bf67-9f24-40b5-a887-5f091eff3961</RoleDatumUuid>
        <RoleDatumUuid>7f8cc197-9f07-45ed-9c49-fa959e39ee5b</RoleDatumUuid>
        <RoleDatumUuid>1bedcedd-fb49-4c37-9417-b37d58eca818</RoleDatumUuid>
        <RoleDatumUuid>5b9b4f41-ea11-4b42-bc5c-d4eb29a3069b</RoleDatumUuid>
        <RoleDatumUuid>7bcb2eb6-8159-440c-821a-5ee5ada18334</RoleDatumUuid>
        <RoleDatumUuid>0aaccaae-a124-4f3e-acdf-f4acf1616ff3</RoleDatumUuid>
        <RoleDatumUuid>26da0186-8ea4-40ed-87e7-e32645be7f25</RoleDatumUuid>
        <RoleDatumUuid>3555088d-cc17-4524-b294-71711fa66d4c</RoleDatumUuid>
        <RoleDatumUuid>95074c74-9a70-4b22-bbd4-cf1182a53243</RoleDatumUuid>
        <RoleDatumUuid>c24ad942-0b1b-45b3-a73c-d98089ad76b7</RoleDatumUuid>
        <RoleDatumUuid>2d8d27d5-ea15-42b0-a873-91263054d751</RoleDatumUuid>
        <RoleDatumUuid>0e057c39-7720-4931-b80b-7d01321f4316</RoleDatumUuid>
        <RoleDatumUuid>a44b24b7-2bec-453f-a3a9-88e31d621f98</RoleDatumUuid>
        <RoleDatumUuid>3022fa29-199c-48b8-b6ce-3762bff952e9</RoleDatumUuid>
        <RoleDatumUuid>c17c43d9-96e0-4401-9800-36f4e40737ae</RoleDatumUuid>
        <RoleDatumUuid>1a11bf17-7335-45a7-a9c7-bbbcfcee22fa</RoleDatumUuid>
        <RoleDatumUuid>03639047-8d4f-4fc0-a0df-1bd20bf01cf1</RoleDatumUuid>
        <RoleDatumUuid>993c6f6c-4cb7-4cb4-874a-6559e7783093</RoleDatumUuid>
        <RoleDatumUuid>24638351-de41-47fe-a7de-d196789602aa</RoleDatumUuid>
        <RoleDatumUuid>ef65d3f5-b16f-47bf-8f36-f5144fa9529e</RoleDatumUuid>
        <RoleDatumUuid>00a6938f-a02d-4664-acd6-320a24c7d8b3</RoleDatumUuid>
        <RoleDatumUuid>efce0383-7068-4ce9-bd86-da1172b259e5</RoleDatumUuid>
        <RoleDatumUuid>637e2e2c-c05f-4297-a24c-7a275768313e</RoleDatumUuid>
        <RoleDatumUuid>535a3a77-2b10-43af-87c6-49b50cf03165</RoleDatumUuid>
        <RoleDatumUuid>323320ea-49aa-47b9-aaa0-36f5fdd8b7bf</RoleDatumUuid>
        <RoleDatumUuid>80fcf98f-91b0-493b-bb7c-32e0d8458b71</RoleDatumUuid>
        <RoleDatumUuid>8d274ac0-3077-45ba-acb7-2eb347c4e330</RoleDatumUuid>
        <RoleDatumUuid>a772e3f4-ddbc-497a-b930-d468ab30f874</RoleDatumUuid>
        <RoleDatumUuid>b4d86a17-affc-433b-8756-3d001550c88a</RoleDatumUuid>
        <RoleDatumUuid>a50a7a96-7023-4bf3-81dc-f2871639bbc2</RoleDatumUuid>
        <RoleDatumUuid>ba6642f2-dbc3-4fbb-8664-b3606ada8a8e</RoleDatumUuid>
        <RoleDatumUuid>2406d650-9ce2-4294-b9e8-091554f9bd71</RoleDatumUuid>
        <RoleDatumUuid>ba0316c5-0b23-4559-b4b9-23e983369f45</RoleDatumUuid>
        <RoleDatumUuid>11f51265-1fd9-46d2-8012-934ef456fab8</RoleDatumUuid>
      </RoleGroup>
    </RoleGroupList>
    <RoleGroupList RoleTypeName="SafetyVariable" />
  </DataList>
</DataListDocument>